services:
  zap-GUI:
    image: ghcr.io/zaproxy/zaproxy:stable
    command: zap-webswing.sh
    user: zap
    ports:
      - "8080:8080"
      - "8090:8090"
    stdin_open: true
    tty: true
  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    command: zap-api-scan.py -f openapi -t http://app-api:3000 -r scan-report.html
    volumes:
      - ./owasp:/zap/wrk/:rw
#    -f format         openapi, soap, or graphql

  # app:
  #   build: .
  #   ports:
  #     - "3000:3000"


  app-api:
    build:
     context: .
     dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
# curl -X POST http://localhost:3000/login -d "username=' OR '1'='1&password=anything"
#  curl "http://localhost:3000/search?q=<script>alert('XSS')</script>"



#docker run -v $(pwd):/zap/wrk/:rw --network="host" zaproxy/zap-stable zap-baseline.py -t https://localhost:8000 -r scan-report.html
#docker run -t ghcr.io/zaproxy/zaproxy:stable zap-full-scan.py -t https://www.example.com

#https://www.zaproxy.org/docs/docker/
